<a href="https://colab.research.google.com/github/Sushantstha2025/np03cs4a240100_AI_Workshop1/blob/main/Workshop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.empty((2,2))
print(arr)

[[4.59766208e-315 0.00000000e+000]
 [4.60230418e-315 7.90505033e-323]]


In [ ]:
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
def new_arr(x, y, z):
  '''
  to generate an array with given shape and fill value

  Params:
  param1: size of row
  param2: size of column
  param3: fill value

  return:
  array with the given shape and fill value
  '''
  return np.full((x, y), z)

arr = new_arr(2,3,7)
zeros_arr = np.zeros_like(arr, dtype=None)  # if dtype = None, it matches the parent dtype in this case, it matches with arr
ones_arr = np.ones_like(arr, dtype=None)
print(arr)
print(zeros_arr)
print(ones_arr)

[[7 7 7]
 [7 7 7]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


In [ ]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arr = np.arange(0,9)
new_arr = arr.reshape((3,3))
print(new_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arr = np.eye(3)   # identity matrix is already a square matrix, so no need to give it the values of row and column, only one value
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from numpy import random
arr = random.randint(100, size= (30))  # first value: range, second value: size of the array
print(np.mean(arr))

50.8


In [ ]:
# Create a 10X10 array with random values and find the minimum and maximum values.
arr = random.randint(100, size=(10,10))
print(np.min(arr))
print(np.max(arr))

0
98


In [ ]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# Reverse an array
arr = [1,2,0,0,4,0]
print(arr[::-1])


[0, 4, 0, 0, 2, 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside.
arr = np.ones((5,5))
arr[1:4, 1:4] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a 8X8 matrix and fill it with a checkerboard pattern.
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1     # fill odd rows, even columns
arr[::2, 1::2] = 1     # fill even rows, odd columns

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(v-w)
print(5*x)
print(x**2)
print(np.dot(x,y))
print(np.dot(x,v))
print(np.dot(v,w))
print(np.vstack((x,y)))  # vstack for row wise concatenation
print(np.hstack((v,w)))  # hstack for column wise concatenation
print(np.concatenate((x,v)))  # throws a ValueError because for concatenation to work, the dimension of both the arrays must be same
# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


[[ 6  8]
 [10 13]]
[-2 -2]
[[ 5 10]
 [15 25]]
[[ 1  4]
 [ 9 25]]
[[19 22]
 [50 58]]
[29 77]
219
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
A = np.array([[3,4],[7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
result1 = np.dot(A,B)
result2 = np.dot(B,A)
print(np.array_equal(result1, result2))  # checks if the arrays are similar

False


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_trans = np.linalg.matrix_transpose(A)
B_trans = np.linalg.matrix_transpose(B)
AB = np.dot(A,B)
AB_trans = np.linalg.matrix_transpose(AB)
result = np.dot(B_trans, A_trans)
print(np.array_equal(AB_trans, result))

True


In [ ]:
A = np.array([[2,-3, 1],
             [1, -1, 2],
             [3, 1, -1]])

B = np.array([-1, -2, 9])
A_inv = np.linalg.inv(A)
x = np.dot(A, B)
print(x)

[ 13  19 -14]


In [ ]:
import time
import numpy as np

start = time.time()
lst = [0] * 1000000
end = time.time()
print(f"it took list {start-end} time to execute")

start = time.time()
arr = np.zeros(1000000, dtype=int)
end = time.time()
print(f"it took numpy array {start-end} time to execute")

it took list -0.04895925521850586 time to execute
it took numpy array -0.00023436546325683594 time to execute


In [ ]:
import time
import numpy as np

start = time.time()
lst1 = [0] * 1000000
lst2 = [1] * 1000000
lst3 = []
for i,j in zip(lst1, lst2):
  lst3.append(i+j)

end = time.time()
print(f"it took list {start-end} time to execute")

start = time.time()
arr1 = np.zeros(1000000, dtype=int)
arr2 = np.ones(1000000, dtype=int)
arr3 = arr1 + arr2
end = time.time()
print(f"it took numpy array {start-end} time to execute")

it took list -0.13439726829528809 time to execute
it took numpy array -0.010054349899291992 time to execute


In [ ]:
import time
import numpy as np

start = time.time()
lst1 = [0] * 1000000
lst2 = [1] * 1000000
lst3 = []
for i,j in zip(lst1, lst2):
  lst3.append(i+j)

lst3 = sum(lst3)
end = time.time()
print(f"it took list {start-end} time to execute")

start = time.time()
arr1 = np.zeros(1000000, dtype=int)
arr2 = np.ones(1000000, dtype=int)
arr3 = np.dot(arr1, arr2)
end = time.time()
print(f"it took numpy array {start-end} time to execute")

it took list -0.13928508758544922 time to execute
it took numpy array -0.005188941955566406 time to execute
